// src/data/categoryOptions.js

export const categoryOptions = [
    { label: 'Afghan', value: 'afghani' },
    { label: 'African', value: 'african' },
    { label: 'American (New)', value: 'newamerican' },
    { label: 'American (Traditional)', value: 'tradamerican' },
    { label: 'Arabic', value: 'arabian' },
    { label: 'Argentine', value: 'argentine' },
    { label: 'Armenian', value: 'armenian' },
    { label: 'Asian Fusion', value: 'asianfusion' },
    { label: 'Austrian', value: 'austrian' },
    { label: 'Bangladeshi', value: 'bangladeshi' },
    { label: 'Barbeque', value: 'bbq' },
    { label: 'Basque', value: 'basque' },
    { label: 'Belgian', value: 'belgian' },
    { label: 'Bistros', value: 'bistros' },
    { label: 'Brazilian', value: 'brazilian' },
    { label: 'Breakfast & Brunch', value: 'breakfast_brunch' },
    { label: 'British', value: 'british' },
    { label: 'Buffets', value: 'buffets' },
    { label: 'Burgers', value: 'burgers' },
    { label: 'Burmese', value: 'burmese' },
    { label: 'Cafes', value: 'cafes' },
    { label: 'Cafeteria', value: 'cafeteria' },
    { label: 'Cajun/Creole', value: 'cajun' },
    { label: 'Cambodian', value: 'cambodian' },
    { label: 'Caribbean', value: 'caribbean' },
    { label: 'Dominican', value: 'dominican' },
    { label: 'Haitian', value: 'haitian' },
    { label: 'Puerto Rican', value: 'puertorican' },
    { label: 'Trinidadian', value: 'trinidadian' },
    { label: 'Cheesesteaks', value: 'cheesesteaks' },
    { label: 'Chicken Shop', value: 'chickenshop' },
    { label: 'Chicken Wings', value: 'chicken_wings' },
    { label: 'Chinese', value: 'chinese' },
    { label: 'Dim Sum', value: 'dimsum' },
    { label: 'Hainan', value: 'hainan' },
    { label: 'Szechuan', value: 'szechuan' },
    { label: 'Comfort Food', value: 'comfortfood' },
    { label: 'Creperies', value: 'creperies' },
    { label: 'Cuban', value: 'cuban' },
    { label: 'Delis', value: 'delis' },
    { label: 'Diners', value: 'diners' },
    { label: 'Dinner Theater', value: 'dinnertheater' },
    { label: 'Eritrean', value: 'eritrean' },
    { label: 'Ethiopian', value: 'ethiopian' },
    { label: 'Fast Food', value: 'hotdogs' },
    { label: 'Filipino', value: 'filipino' },
    { label: 'Fish & Chips', value: 'fishnchips' },
    { label: 'Fondue', value: 'fondue' },
    { label: 'Food Court', value: 'food_court' },
    { label: 'French', value: 'french' },
    { label: 'Gastropubs', value: 'gastropubs' },
    { label: 'Georgian', value: 'georgian' },
    { label: 'German', value: 'german' },
    { label: 'Gluten-Free', value: 'gluten_free' },
    { label: 'Greek', value: 'greek' },
    { label: 'Halal', value: 'halal' },
    { label: 'Hawaiian', value: 'hawaiian' },
    { label: 'Hot Dogs', value: 'hotdog' },
    { label: 'Hot Pot', value: 'hotpot' },
    { label: 'Hungarian', value: 'hungarian' },
    { label: 'Indian', value: 'indpak' },
    { label: 'Irish', value: 'irish' },
    { label: 'Italian', value: 'italian' },
    { label: 'Japanese', value: 'japanese' },
    { label: 'Korean', value: 'korean' },
    { label: 'Kosher', value: 'kosher' },
    { label: 'Latin American', value: 'latin' },
    { label: 'Mediterranean', value: 'mediterranean' },
    { label: 'Mexican', value: 'mexican' },
    { label: 'Middle Eastern', value: 'mideastern' },
    { label: 'Modern European', value: 'modern_european' },
    { label: 'Pakistani', value: 'pakistani' },
    { label: 'Persian/Iranian', value: 'persian' },
    { label: 'Pizza', value: 'pizza' },
    { label: 'Polish', value: 'polish' },
    { label: 'Portuguese', value: 'portuguese' },
    { label: 'Russian', value: 'russian' },
    { label: 'Salad', value: 'salad' },
    { label: 'Sandwiches', value: 'sandwiches' },
    { label: 'Seafood', value: 'seafood' },
    { label: 'Senegalese', value: 'senegalese' },
    { label: 'Soup', value: 'soup' },
    { label: 'South African', value: 'southafrican' },
    { label: 'Southern', value: 'southern' },
    { label: 'Spanish', value: 'spanish' },
    { label: 'Steakhouses', value: 'steak' },
    { label: 'Sushi Bars', value: 'sushi' },
    { label: 'Thai', value: 'thai' },
    { label: 'Turkish', value: 'turkish' },
    { label: 'Vegan', value: 'vegan' },
    { label: 'Vegetarian', value: 'vegetarian' },
    { label: 'Vietnamese', value: 'vietnamese' },
  ];
  